### ISSUE TITLE
.mat-spinner is spinning off axis because of CSS padding instead of margin?

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Blog#38]

**Comment by BryanWilhite** [comment]
nope:

```scss
.mat-spinner {
    margin: 1rem auto;
    min-height: 8rem;
}
```
